### ISSUE TITLE
Class 'ST\Assignees' not found

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticTasks#24]
### Setup and configuration

- MediaWiki | 1.34.0-rc.0 (366bf66)22:03, 15 October 2019
- PHP | 7.2.19-0ubuntu0.18.04.2 (apache2handler)
- MariaDB | 10.1.41-MariaDB-0ubuntu0.18.04.1
- Semantic Tasks master

### Issue
```
Error from line 65 of /../w/extensions/SemanticTasks/SemanticTasks.php: Class 'ST\Assignees' not found
```
This happens after upgrading from MW 1.33 to MW 1.34

### Backtrace
```
#0 /../w/includes/Setup.php(896): SemanticTasks::onExtensionFunction()
#1 /../w/maintenance/doMaintenance.php(83): require_once(string)
#2 /../w/maintenance/update.php(277): require_once(string)
#3 {main}
```

**Comment by PeterTheOne** [comment]
Did something change with 1.34 about how classes are included?

**Comment by kghbln** [comment]
> Did something change with 1.34 about how classes are included?

I have no idea. @JeroenDeDauw ?

**Comment by JeroenDeDauw** [comment]
Think something went wrong with setup when you encountered this error, rather than there being a problem with the extension.

Maybe it was removed from composer.local.json. Maybe the setup was using this no longer needed hack before (https://github.com/SemanticMediaWiki/SemanticTasks/blob/master/SemanticTasks.php#L20) and now broke due to some changes in MW.

Would double check composer.local.json and rebuild the autoloader if the problem is still there.

**Comment by kghbln** [comment]
> Think something went wrong with setup when you encountered this error, rather than there being a problem with the extension.

This may very well be. The upgrade to MW 1.34 was a complete disaster with many extension creating many issues. I just opened bug reports and dumped the shit that was washed up at my end.

I have now reinstalled the extension with current master and invoked it. At least I am not getting any fatals etc. from the [example page](https://sandbox.semantic-mediawiki.org/wiki/Semantic_Tasks_assignments). I do have to note that I have not the slightest idea if it is working or not.
